name: Integrity

on:
  pull_request:
  push:
    branches-ignore: [master]

jobs:
  integrity:
    name: Integrity

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Install Yarn dependencies
        run: yarn install

      - name: Compile rules
        run: |
          php gen currencies
          php gen numbers
          php gen units

      - name: Check for uncommitted changes
        run: git add . && git diff --cached --exit-code
